module(
    name = "cc_toolchains_windows",
    version = "20260521.15-dev",
)

bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "bazel_skylib", version = "1.9.0")
bazel_dep(name = "rules_cc", version = "0.2.18")
bazel_dep(name = "googletest", version = "1.17.0.bcr.2")

register_execution_platforms(
    "@cc_toolchains_windows//:windows_x86",
    "@cc_toolchains_windows//:windows",
)

register_toolchains(
    "@cc_toolchains_windows//:windows_x86_toolchain",
    "@cc_toolchains_windows//:windows_toolchain",
)
